apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: project-tory
spec:
  destinations:
  - name: ## cluster name
    namespace: b2b
    server: ## cluster server url
  sourceRepos:
  - ## http git repo url
status: {}
