apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: ci
spec:
  description: ci
  destinations:
  - namespace: ci
    server: https://kubernetes.default.svc
  sourceRepos:
  - https://kubernetes-charts.storage.googleapis.com
  - https://charts.jenkins.io
  - http://bitbucket.11stcorp.com/scm/eks/argocd-deploy-ci-jenkins.git
