apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: locust
spec:
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  destinations:
  - name: 11st-dev-green-v1
    namespace: locust
    server:
  sourceRepos:
  -
status: {}
