apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: sitespeedio
spec:
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  destinations:
  - namespace: '*'
    server: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  - group: ""
    kind: ""
  sourceRepos:
  - http://bitbucket.11stcorp.com/scm/cloud/sitespeedio-charts.git
status: {}
