apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: b2b-auth-dev
spec:
  destination:
    namespace: b2b
    name: 11st-dev-green-v1
  project: b2b-auth
  source:
    path: kustomization/overlays/dev
    repoURL: http://bitbucket.11stcorp.com/scm/eks/argocd-deploy-b2b-auth.git
    targetRevision: HEAD
  syncPolicy:
    automated: {}
