apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: b2b-auth-prod
  annotations:
    notifications.argoproj.io/subscribe.on-health-suspended.slack: eks_slack_test_channel
spec:
  destination:
    namespace: b2b
    name: 11st-prod-green-v1
  project: b2b-auth
  source:
    path: kustomization/overlays/prod
    repoURL: http://bitbucket.11stcorp.com/scm/eks/argocd-deploy-b2b-auth.git
    targetRevision: HEAD
