apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: application-tory
spec:
  destination:
    namespace: b2b
    name: ## cluster name
  project: ## project name
  source:
    path: kustomization/overlays/dev ## kustomization.yaml path
    repoURL:  ## http git repo url
    targetRevision: HEAD
  syncPolicy:
    automated: {}
