apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mario-kook #ArgoCD Application의 Name
spec:
  project: mario #ArgoCD Project를 지정합니다.
  source:
    repoURL: http://bitbucket.11stcorp.com/scm/eks/argocd-deploy-sample-app.git #배포 정의 Code가 담긴 deployment Repository
    path: kustomization-kook/overlays/dev #kustomization 구조에서 해당 Application이 실제로 바라볼 path
    targetRevision: HEAD #Branch name (master, HEAD. . .)
  destination:
    namespace: sample #배포 대상 클러스터의 namespace
    name: 11st-dev-green-v1 #배포 대상 클러스터 name