apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: chatbot-dev
spec:
  destination:
    namespace: chatbot
    name: 11st-dev-green-v1
  project: chatbot
  source:
    path: app/chatbot/kustomization/overlays/dev
    repoURL: http://bitbucket.11stcorp.com/scm/cloud/argocd-env-service.git
    targetRevision: HEAD
  syncPolicy: {}
