apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tour-hpa-alp
spec:
  destination:
    namespace: tour
    name: 11st-alpha-green-v1
  project: apptour
  source:
    path: app/apptour/kustomization/overlays/alp
    repoURL: http://bitbucket.11stcorp.com/scm/cloud/argocd-env-service.git
    targetRevision: HEAD
  syncPolicy: {}